# function app deployment
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: cloud-eng

steps:
- task: UsePythonVersion@0
  displayName: "Setting python version to 3.7 as required by functions"
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'
- bash: |
    cd 3_coding
    python3.7 -m venv worker_venv
    source worker_venv/bin/activate
    pip install setuptools
    pip install -r requirements.txt
    # pip install --target="./.python_packages/lib/site-packages" -r ./3_coding/requirements.txt
- task: ArchiveFiles@2
  displayName: "Archive files"
  inputs:
    rootFolderOrFile: "$(System.DefaultWorkingDirectory)/3_coding"
    includeRootFolder: false
    archiveFile: "$(System.ArtifactsDirectory)/build$(Build.BuildId).zip"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.ArtifactsDirectory)/build$(Build.BuildId).zip'
    artifactName: 'drop'

- task: AzureFunctionApp@1 
  inputs:
    azureSubscription: $(serviceConnectionName)
    appType: functionAppLinux 
    appName: $(appName)
    package: $(System.ArtifactsDirectory)/**/*.zip